[package]
name = "skima-rsx"
authors = ["Stanislav Panferov <stanislav@panferov.dev>"]
version="0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*" 
quote = "*"
syn = "*"
syn-rsx = "*"

